apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Values.siteminder.apache.name }}
spec:
  type: LoadBalancer
  ports:
    - name: "2443"
      port: 2443
      targetPort: 443
    - name: "2080"
      port: 2080
      targetPort: 80
  selector:
    app: {{ .Values.siteminder.apache.name }}
status:
  loadBalancer: {}
