apiVersion: v1
kind: Secret
metadata:
  name: rapidsso-sm-credentials
data:
  secret: {{ .Values.siteminder.secret }}
  username: {{ .Values.siteminder.username }}
  password: {{ .Values.siteminder.password }}
type: Clear
