apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Values.siteminder.ag.name }}
spec:
  type: LoadBalancer
  ports:
    - name: "443"
      port: 443
      targetPort: 443
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.siteminder.ag.name }}
status:
  loadBalancer: {}
